name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            echo "No requirements.txt found"
          fi

      - name: Create dataset cache directory
        run: |
          mkdir -p data/raw/m5-forecasting-accuracy

      - name: Restore M5 dataset cache
        id: cache-m5
        uses: actions/cache@v5
        with:
          path: data/raw/m5-forecasting-accuracy
          key: ${{ runner.os }}-m5-forecasting-accuracy-v1

      - name: Download dataset if cache is missing
        if: steps.cache-m5.outputs.cache-hit != 'true'
        env:
          KAGGLE_API_TOKEN: ${{ secrets.KAGGLE_API_TOKEN }}
        run: |
          if [ -z "$KAGGLE_API_TOKEN" ]; then
            echo "KAGGLE_API_TOKEN secret is missing."
            echo "Skipping dataset download in CI."
            exit 0
          fi

          python scripts/0.download_dataset.py

      - name: Check Python syntax
        run: |
          python -m compileall scripts models notebooks

      - name: Check raw dataset is not committed
        run: |
          if git ls-files | grep -E "(sales_train|sell_prices|calendar|sample_submission).*\.csv$"; then
            echo "ERROR: Raw dataset CSV files are committed to Git."
            exit 1
          else
            echo "No raw dataset CSV files are committed."
          fi

      - name: Run tests if available
        run: |
          if [ -d tests ]; then
            pip install pytest
            pytest
          else
            echo "No tests folder found. Skipping tests."
          fi